spring:
  cloud:
    config:
        server:
          git: 
            uri: https://github.com/CarlossVasquezCasas/config-server
            search-paths:
             Configuracion
server: 
  port: 8800  
#server: 
#  port: 8081  